### ISSUE TITLE
mysql  apt-key timeout 

### ISSUE THREAD

**Issue by tqf6** [Websoft9/ansible-ruby#3]
## Language

- [ ] Chinese
- [ ] English

## Content error

Provide us with documentation errors, e.g spelling mistake, wrong screenshot, code syntax error.

* URL: 
* Description: 
* Screenshot

## Content optimization

Provide us with content optimization, e.g easy to read, simplify the steps, step by step, precise expression.

* URL: 
* Description: 

## New content

Describe important content what do you think is important in this documentation.

**What content do you want to add?**  

(describe here) 

**Steps for the content**  

![image](https://user-images.githubusercontent.com/83911329/123078951-0fa5e500-d44e-11eb-9189-ec4351a73c39.png)

4. Modify file '....'

**Comment by qiaofeng1227** [comment]
- pgp.mit.edu
- keys.gnupg.net

always need to switch one to another
