### ISSUE TITLE
文档补全及错误更正

### ISSUE THREAD

**Issue by morning-tan** [Websoft9/ansible-ruby#5]
## Language

- [ ] Chinese
- [x] English

## Content error

Overview部分关于产品介绍错误。

* URL: https://support.websoft9.com/docs/ruby/#improve
* Description:  “Ruby is the most widely deployed open source message broker. ”

Applications Deployment链接跳转404。

* Screenshot
![image](https://user-images.githubusercontent.com/54173243/124345766-627d5a80-dc0d-11eb-95bf-20044a41bc2a.png)

## Content optimization

9panel面板提供MongoDB与MySQL可视化工具入口，但在文档里未提及adminMongo端口9091，是否应补充至表格？

* URL: https://support.websoft9.com/docs/ruby/stack-components.html#ports

安装部署章节需补全

## New content

Describe important content what do you think is important in this documentation.

**What content do you want to add?**  

(describe here) 

**Steps for the content**  

4. Modify file '....'

**Comment by qiaofeng1227** [comment]
Done
