### ISSUE TITLE
Can't access Rails example page

### ISSUE THREAD

**Issue by morning-tan** [Websoft9/ansible-ruby#9]
**Describe the bug**

The Rails example page is not accessible by accessing the URL http://DNS and http://Instance's Internet IP:3000

## Deployment method

- [ ] subscription image from MarketPlace of Cloud
- [ ] All-in-one Installer
- [ ] ansible-playbook cli
- [x] mcloud
- [ ] create instance from private image

## Bug source

- [x] Bugs from installation 
- [ ] Bugs from first use
- [ ] Other (You should describe it)   

## System Environment

**Application Version**

ruby3.0-amazonlinux2

**OS**

- [ ] Ubuntu18.x
- [ ] Ubuntu20.x
- [ ] CentOS7.x
- [ ] CentOS8.x
- [x] AmazonLinux2
- [ ] OracleLinux7.8
- [ ] OracleLinux8.2
- [ ] Other (You should describe it) 

**Cloud PlatForm**

- [ ] Azure
- [x] Aws
- [ ] 阿里云
- [ ] 腾讯云
- [ ] 华为云
- [ ] AlibabaCloud
- [ ] HUWEICloud
- [ ] Other (You should describe it) 

### Bug Context

Bug context includes bug error, error logs and service status, it is very important for resolving issue

```
# bug error
(paste here) 

# service status 
(paste here) 

# error logs
(paste here) 
```

### Bug Screenshot

paste screenshot here

## Your suggestion

**The reason of Bug**

You can describe the reason if you have found it

**Your solution for Bug**

You can describe your solution here

**Additional context**

You can add any other context about the problem here.

**Comment by qiaofeng1227** [comment]
rails service is not running
```
[root@ip-172-31-7-49 myrails]# systemctl status rails
● rails.service - Rails Service
   Loaded: loaded (/usr/lib/systemd/system/rails.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Thu 2022-02-10 00:47:24 UTC; 4s ago
  Process: 18863 ExecStart=/usr/bin/bash -lc rails s -p 3000 -b 0.0.0.0 (code=exited, status=1/FAILURE)
 Main PID: 18863 (code=exited, status=1/FAILURE)

Feb 10 00:47:24 ip-172-31-7-49.ec2.internal systemd[1]: Unit rails.service entered failed state.
Feb 10 00:47:24 ip-172-31-7-49.ec2.internal systemd[1]: rails.service failed.
```

**Comment by qiaofeng1227** [comment]
https://github.com/rails/rails/tree/v7.0.2
```
 bin/rails server
```

**Comment by qiaofeng1227** [comment]
```
[Unit]
Description=Rails Service
Requires=network.target
 
[Service]
Type=simple
Environment=RAILS_ENV=development
PIDFile={{ruby_applications_rails.path}}/rails.pid
WorkingDirectory={{ruby_applications_rails.path}}/{{ruby_applications_rails.project}}
ExecStart=/usr/bin/bash -lc "rails server -p {{ruby_applications_rails.port}} -b 0.0.0.0"
TimeoutSec=30
RestartSec=15s
Restart=always
 
[Install]
WantedBy=multi-user.target
```

**Comment by qiaofeng1227** [comment]
rails:6.1.4 OK
gem install rails -v 6.1.4
